# CI/CD

image: archlinux
packages:
  - rustup
sources:
  - https://git.sr.ht/~hadronized/kak-tree-sitter
tasks:
  - setup: |
      rustup set profile minimal
      rustup default stable
      rustup component add rustfmt clippy

  - check-default: |
      cd kak-tree-sitter
      cargo fmt --check
      cargo clippy
  - check-all-features: |
      cd kak-tree-sitter
      cargo clippy --all-features

  # up-to-date build
  - build-default: |
      cd kak-tree-sitter
      cargo build
  - build-all-features: |
      cd kak-tree-sitter
      cargo build --all-features
  - test-default: |
      cd kak-tree-sitter
      cargo test
  - test-all-features: |
      cd kak-tree-sitter
      cargo test --all-features

  # minimal version build
  - build-minimal-default: |
      rustup default nightly
      cd kak-tree-sitter
      cargo build -Z minimal-versions
  - build-minimal-all-features: |
      rustup default nightly
      cd kak-tree-sitter
      cargo build -Z minimal-versions --all-features
  - test-minimal-default: |
      rustup default nightly
      cd kak-tree-sitter
      cargo test -Z minimal-versions
  - test-minimal-all-features: |
      rustup default nightly
      cd kak-tree-sitter
      cargo test -Z minimal-versions --all-features
