# CI/CD

image: archlinux
packages:
  - rustup
sources:
  - https://git.sr.ht/~hadronized/kak-tree-sitter
tasks:
  - setup: |
      rustup set profile minimal
      rustup default stable
      rustup component add rustfmt clippy

  - check: |
      cd kak-tree-sitter
      cargo fmt --check
      cargo clippy

  # up-to-date build
  - build: |
      cd kak-tree-sitter
      cargo build
  - test: |
      cd kak-tree-sitter
      cargo test

  # minimal version build
  - build-minimal: |
      rustup default nightly
      cd kak-tree-sitter
      cargo build -Z minimal-versions
  - test-minimal: |
      rustup default nightly
      cd kak-tree-sitter
      cargo test -Z minimal-versions
